### ISSUE TITLE
Make bracketed paste optional

### ISSUE THREAD

**Issue by glguy** [coreyoconnor/vty#100]
Bracketed paste is pretty cool. I can see lots of opportunities for clever functionality with it.

However there are other cases where I don't want to treat pastes specially. Is there a way I could disable Paste events and recover the old behavior to avoid simply having to write extra logic to reinterpret paste events as a series of key events?

**Comment by jtdaugherty** [comment]
The parts to this that I can think of are:
* Initial configuration (e.g. add an option to `Config` like `bracketedPasteMode` defaulting to `True` and then make `outputForConfig` use that to determine whether paste mode is enabled initially)
* Reconfiguration (the application would need to enable and disable this as appropriate as `vim` does with `:set paste`, so add a field to `Vty` called `setBracketedPasteMode :: Bool -> IO ()`)
* Querying (to avoid making the application track the state of this, add a field to `Vty` called `getBracketedPasteMode :: IO Bool`)

**Comment by jtdaugherty** [comment]
Would that sort of API work for you?

**Comment by glguy** [comment]
The ability to inspect and update the setting at runtime is even more I'd
hoped for and sounds lovely.

(Incidentally I'm in the process of making my IRC client take advantage of
this neat new functionality.)

**Comment by jtdaugherty** [comment]
This is now implemented in https://github.com/coreyoconnor/vty/commit/d4789578eda60a80cde7f3c12cc3a6a31c11049f.

**Comment by jtdaugherty** [comment]
(In particular, to be courteous these modes are now disabled by default.)

**Comment by jtdaugherty** [comment]
Another note is that this will only allow these modes to be enabled in xterm-like terminals (`TERM` looks like `xterm` or `screen`); terminals that use the `TerminfoBased` driver don't support these modes yet. That's because terminfo doesn't expose capabilities for these modes so I can't safely enable them.

**Comment by jtdaugherty** [comment]
Also note the new `ModeDemo.hs` program I added to show how this works.

**Comment by jtdaugherty** [comment]
Let me know what you think. If this is looking good, I can cut a release today.

**Comment by glguy** [comment]
Looks good to me! I didn't exhaustively test it but I like the API and when I build my client against this new version things work like they used to (and once I finish the new paste logic I'll be able to turn that on)

**Comment by jtdaugherty** [comment]
This is now released: http://hackage.haskell.org/package/vty-5.7
