### ISSUE TITLE
Make mouse support optional

### ISSUE THREAD

**Issue by glguy** [coreyoconnor/vty#101]
Mouse support also sounds pretty cool, but putting the terminal into mouse mode seems to mean that I can't select text any more. My cursor is permanently in crosshair mode instead of text-select mode.

I'm testing this using the macOS Terminal.app

Could this functionality get the same treatment as the bracketed paste?

**Comment by jtdaugherty** [comment]
Yep, I think the same approach can be used here.

**Comment by jtdaugherty** [comment]
This is now implemented in https://github.com/coreyoconnor/vty/commit/d4789578eda60a80cde7f3c12cc3a6a31c11049f.

**Comment by jtdaugherty** [comment]
This is now released: http://hackage.haskell.org/package/vty-5.7
