### ISSUE TITLE
Expose method for terminal beep

### ISSUE THREAD

**Issue by glguy** [coreyoconnor/vty#102]
Is there a portable way to handle audible alerts to the terminal? A brief look at the terminfo database seemed to indicate that bell functionality was described there.

Currently I'm using

```haskell
beep :: Vty -> IO ()
beep vty = outputByteBuffer (outputIface vty) "\BEL"
```

because it works for my case, but I imagine this isn't going to work on all the terminal types that VTY supports.

It's also possible that there's already a good way to do this with VTY and I've just missed it.

**Comment by jtdaugherty** [comment]
Is it important to know whether the terminal supports it? Or is it just important to have a way to ring the bell (if supported)?

**Comment by glguy** [comment]
I think that the most important thing is to have an abstraction for "notify the user" whatever that happens to mean for the terminal. My particular use-case doesn't require me to know if bell is supported, though I could imagine someone needing that.

I think that any attempt at actually characterizing what the terminal supports would best fit into a generalized terminal capability query interface. (VTY might have this somewhere but I don't know about it) where you could ask about all manner of capabilities: supported colors, supported modes, supported inputs, etc. I wouldn't want to stall support for notifying the user on that functionality, though.

**Comment by jtdaugherty** [comment]
There are two kinds of bells. Right now I'm trying out this interface:

``` haskell
data BellType = Audio | Visual

ringTerminalBell Audio (outputIface vty)
```

Thoughts?

**Comment by glguy** [comment]
I think that sounds lovely. It would be quite reasonable to defer the decision about which bell to use to the client application where the client user could configure what kind of bell they'd like where appropriate (with the application developer making a default choice).

**Comment by jtdaugherty** [comment]
I'm also adding

``` haskell
supportsBell :: Output -> BellType -> IO Bool
```

to let you access the probing results. Then you'll know which `ringTerminalBell` calls will be useful.

**Comment by jtdaugherty** [comment]
Unfortunately the visual bell (terminfo capability `flash`) doesn't work for me on either iTerm2 or Terminal.app, but the audio bell works on both.  So for now I'll just add audio bell support.

**Comment by jtdaugherty** [comment]
This is now released as 5.9.

**Comment by glguy** [comment]
I was able to generate a terminal visual bell on Terminal.app as follows

``` haskell
import System.Console.Terminfo

main :: IO ()
main =
  do t <- setupTermFromEnv
     case getCapability t visualBell of
       Nothing -> putStrLn "Not supported"
       Just out -> runTermOutput t out
```

I went looking because Terminal.app has this setting

![screen shot 2016-08-28 at 10 38 47 am](https://cloud.githubusercontent.com/assets/12164/18035484/a2d91112-6d0b-11e6-972a-5458f0fcbd7d.png)

**Comment by jtdaugherty** [comment]
Interesting. Vty parses terminfo from the disk file. Does `setupTermFromEnv` somehow get the capability more dynamically? (I.e. as affected by the settings you showed.)

**Comment by glguy** [comment]
I don't see any special case, it just appears to look up the terminfo setting for `"flash"`. I'll keep poking.

**Comment by glguy** [comment]
I made a small C program that flashes the terminal using terminfo. It's important to emit the flash using putp in the case of C, or using runTermOutput in the case of terminfo, it's insufficient to print the resulting string directly (though I don't know why that is yet)

``` c
#include <term.h>
int main () {
        setupterm((char *)0, 1, (int *)0);
        putp(tigetstr("flash"));
}
```

I tried printing the terminfo entry for flash directly and it doesn't work as shown here (N.B. the terminal didn't flash):

``` haskell
Prelude> putStrLn "\x1b\x5b\x3f\x35\x68\x24\x3c\x31\x30\x30\x2f\x3e\x1b\x5b\x3f\x35\x6c\x0a"
$<100/>
```
