### ISSUE TITLE
Paste events have UTF-8 encodings instead of Unicode codepoints

### ISSUE THREAD

**Issue by glguy** [coreyoconnor/vty#103]
With paste events off pasting `‘` I get

```
(EvKey (KChar '\8216') []
```

but with paste events on I get

```
(EvPaste "\226\128\152") 
```

Is this intentional?

**Comment by jtdaugherty** [comment]
This has been fixed in https://github.com/coreyoconnor/vty/commit/b5115c881cb8a0bdcd2940a30d86bdfadc398a88 and is released on Hackage as version 5.8.
