### ISSUE TITLE
minor: shutdown does not reset display to previous settings

### ISSUE THREAD

**Issue by Mikolaj** [coreyoconnor/vty#33]
Not sure if it's gnome terminal or vty problem, I didn't find a way to test anything similar with xterm. My gnome terminal is semi-transparent. My program runs with a solid black baground. When exit my program and them do 'less file', the background again goes solid black. When I type 'reset' and do 'less file' it's semi-transparent again. The same code with hscurses instead of vty restores the transparency OK.

Here's the line where I call shutdown:

https://github.com/kosmikus/LambdaHack/blob/2993557505762fb955408e96f1ec7ef5acb6694e/Game/LambdaHack/Action/Frontend/Vty.hs#L32

and the analogous place for the hscurses frontend:

https://github.com/kosmikus/LambdaHack/blob/2993557505762fb955408e96f1ec7ef5acb6694e/Game/LambdaHack/Action/Frontend/Curses.hs#L53

Perhaps related: with hscurses, when I run the program, only the part of the screen I'm writing to gets the black baground, with vty, the whole screen turns black.

**Comment by jtdaugherty** [comment]
@Mikolaj - a similar issue reported in #15 is now resolved, so I'm wondering whether this also works for you.  If you try this with the latest `vty` on Hackage, what is the result?

**Comment by Mikolaj** [comment]
Yep, the newest version restores terminal state perfectly now. Thank you! Closing.
