### ISSUE TITLE
Consider using TChan rather than Chan

### ISSUE THREAD

**Issue by Fuuzetsu** [coreyoconnor/vty#60]
Graphics.Vty.Input.Loop uses `Chan` so when the library user wants to check if the channel is empty, they get 

```
src/library/Yi/UI/Vty.hs:80:41: Warning:
    In the use of ‘isEmptyChan’
    (imported from Control.Concurrent, but defined in Control.Concurrent.Chan):
    Deprecated: "if you need this operation, use Control.Concurrent.STM.TChan instead.  See <http://ghc.haskell.org/trac/ghc/ticket/4154> for details"
```

**Comment by jtdaugherty** [comment]
@coreyoconnor - I've pushed a patch to do this to the feature/stmchans branch. Can you take a look?

**Comment by coreyoconnor** [comment]
Looks fine to me. Thanks! Bumped version to 5.4 due to the change in eventChannel type.
