### ISSUE TITLE
256 color on OS X requires unsetting TERM_PROGRAM

### ISSUE THREAD

**Issue by glguy** [coreyoconnor/vty#68]
For a few versions of OS X I've needed to unset the TERM_PROGRAM environment variable to enable 256 color mode on OS X. Detecting this variable might have made sense in the past but it's not relevant today.

**Comment by coreyoconnor** [comment]
Thanks for the bug report and pull request!
A fix for the bug and the pull request are included in vty 5.2.8:
* http://hackage.haskell.org/package/vty-5.2.8
