### ISSUE TITLE
Module configuration fails with Cabal 1.20

### ISSUE THREAD

**Issue by danse** [coreyoconnor/vty#75]
Hello, maybe this is not a problem in `vty`, but the error i get is not very helpful:
```
 tmp $ cabal install vty
Resolving dependencies...
Notice: installing into a sandbox located at /tmp/.cabal-sandbox
Configuring base-orphans-0.3.2...

... omitted ...

Building lens-4.11...
Installed lens-4.11
Configuring vty-5.2.9...
Failed to install vty-5.2.9
Build log ( /tmp/.cabal-sandbox/logs/vty-5.2.9.log ):
cabal: Error: some packages failed to install:
vty-5.2.9 failed during the configure step. The exception was:
user error (The package 'vty' requires Cabal library version -any && >=1.18.0
but no suitable version is installed.)
 tmp $ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 
tmp $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```
I realise that i have quite an old version of the compiler, but maybe that has nothing to do with the problem

**Comment by coreyoconnor** [comment]
What Cabal library is in play is troublesome to figure out. In this case: The Cabal library being used is not the one `cabal --version` prints the version for. `cabal --version` will print the version of the Cabal library used to compile cabal-install. Which can be different than the version of Cabal available to projects. TO check the version of Cabal available to projects use `ghc-pkg list Cabal`. That will list out all Cabal libraries that projects can compile against.

My hypothesis is: If you execute `ghc-pkg list Cabal` then you will find an old ( < 1.18) version of Cabal in the package library. `cabal install Cabal` might resolve this.

**Comment by jtdaugherty** [comment]
One might also try `cabal update` in case the package database is old enough that `cabal-install` doesn't know about `Cabal >= 1.18.0`.

**Comment by danse** [comment]
> What Cabal library is in play is troublesome to figure out. In this case: The Cabal library being used is not the one cabal --version prints the version for. cabal --version will print the version of the Cabal library used to compile cabal-install. Which can be different than the version of Cabal available to projects 

Weird, `cabal --version` seems to clearly list both the version used for compiling `cabal-install` and the library version:

```sh
 tmp $ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 
```

Anyway, this is clearly not an issue with this package

**Comment by danse** [comment]
I do not have that machine available anymore. Anyway, thanks for the hint about `ghc-pkg list Cabal`, that is the right command one should use for troubleshooting!
