### ISSUE TITLE
Background color behavior unexpected with translation

### ISSUE THREAD

**Issue by jtdaugherty** [coreyoconnor/vty#76]
The following program misbehaves for me with `5.2.9`, iTerm2 on OS X.

The actual behavior: the 10 columns to the left of the green region has a blue background.
The expected behavior: the 10 columns to the left of the green region has the default background.

It looks like the background from the line above is overrunning into the space created by the translation operation.
```
module Main where

import Control.Monad (void)
import Graphics.Vty

main :: IO ()
main = do
     cfg <- standardIOConfig
     vty <- mkVty cfg
     let line1 = charFill (defAttr `withBackColor` blue) ' ' 10 1
         line2 = charFill (defAttr `withBackColor` green) ' ' 10 1
         img = translate 10 5 (line1 `vertJoin` line2)
         pic = picForImage img

     update vty pic
     void $ nextEvent vty
     shutdown vty
```

**Comment by coreyoconnor** [comment]
Thanks for the regression test! Added as test/Issue76.hs
