### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jtdaugherty** [coreyoconnor/vty#79]
Would you be willing to tag releases, e.g., `5.2.10`?  That way it becomes much easier to tell when a release is available and how to look for changes in a release in case the `CHANGELOG` has not been updated.

**Comment by coreyoconnor** [comment]
Sure!
I've released the latest set of pull requests as 5.2.11 to hackage. I've tagged this as 5.2.11. Re-open if this process is not quite right. :-)

**Comment by jtdaugherty** [comment]
Thank you!
