### ISSUE TITLE
add to stackage ?

### ISSUE THREAD

**Issue by simonmichael** [coreyoconnor/vty#84]
Thank you for this great library. Could it be added to stackage ? On general principles, and also I'd like to add it as a core dependency of hledger on non-windows platforms; because it's not in stackage I need to list it in extra-deps for the stack tool; because this can't be conditionalised I'll need to provide a separate stack.yaml file for windows users. (PS: any hope for vty working on native MS Windows ?)

**Comment by jtdaugherty** [comment]
I've added `vty` to stackage:

https://github.com/fpco/stackage/pull/751

**Comment by jtdaugherty** [comment]
Would you be willing to open other issues for e.g. Windows support? I'd like to close this one and keep issues about one topic each.

**Comment by simonmichael** [comment]
Wonderful, brick as well! Thanks.
