### ISSUE TITLE
Discontinue dependency on lens

### ISSUE THREAD

**Issue by jtdaugherty** [coreyoconnor/vty#90]
Since `vty` doesn't use `lens` for much at all and since `lens` greatly increases the dependency load for installing `vty`, I'm wondering whether @coreyoconnor would be okay with changes to back out usage of `lens` and removal of `lens` as a dependency.

**Comment by jtdaugherty** [comment]
(If these changes have approval, I'll probably be able to get to them in the next week or so.)

**Comment by jtdaugherty** [comment]
Alternatively, a `lens`-compatible library with a smaller dependency load could be used, such as `microlens`.

**Comment by simonmichael** [comment]
+1 for the quicker-building microlens, if it's sufficient; this would make installation of hledger-ui quicker. The license is the same (BSD3).

**Comment by coreyoconnor** [comment]
Removing unneeded dependencies is definitely valuable. +1 to either

**Comment by jtdaugherty** [comment]
I'll start on a patch shortly, then. Thanks!

**Comment by jtdaugherty** [comment]
@coreyoconnor - this is now done on the https://github.com/coreyoconnor/vty/tree/refactor/microlens-migration branch. The only relevant commit is https://github.com/coreyoconnor/vty/commit/0c9d54f960a2f14b5d0c8ee736a8e1511c81f090. I'll await feedback or confirmation that it looks good before I merge to `master`.

**Comment by jtdaugherty** [comment]
After a bugfix for GHC 7.6/7.8, the build looks good (aside from the continuing out-of-memory error on GHC 7.4).

**Comment by ethercrow** [comment]
I've looked at travis build and thought it was suspicious that build time is so different between 7.8 and 7.10. Turned out we have a broken version comparison that considers 7.10 < 7.2. I (hopefully) just fixed it in https://github.com/ethercrow/vty/commits/master, still waiting for travis to complete.

**Comment by simonmichael** [comment]
Any news on this ?

I can confirm that microlens builds with GHC 8 rc4 but lens [doesn't yet](https://github.com/ekmett/lens/issues/652).

**Comment by glguy** [comment]
No need to switch now, lens-4.14 is released and builds on GHC 8 rc4

**Comment by coreyoconnor** [comment]
Change for using microlens: LGTM.

I haven't kept up with lens/microlens. Will adding microlens to vty cause any conflict in packages that depend on vty and lens?

**Comment by jtdaugherty** [comment]
@coreyoconnor I don't know how to answer that question generally, but I doubt it.  (And even if so, the risk of that is smaller than with `lens`, given `lens`'s dependency set.)

Do I have sign-off to merge?

**Comment by coreyoconnor** [comment]
Yes. Go ahead with the merge.

I think my question is not applicable to Haskell. :) this is what Scala
does to the brain ;)

**Comment by jtdaugherty** [comment]
Merged. Thanks!

**Comment by jtdaugherty** [comment]
(Also, note: I did not bump the package version or update the changelog yet as I tend to do those things only at release time once the version number change can be motivated. But obviously this merge justifies a bump in the second component. Right now the cabal file is ahead of the released version but will need to be advanced further to `5.5.0` at release time.)
