### ISSUE TITLE
Release vty 5.5.0

### ISSUE THREAD

**Issue by jtdaugherty** [coreyoconnor/vty#93]
I'd like to get the migration from `lens` to `microlens` released on Hackage so I can release a similar upgrade to `brick`.  Although I have privileges on the Git repository I don't have Hackage upload permission.  What's the roadmap for the next release?  Can we get a new one out soon?

Thanks!

CC @simonmichael

**Comment by coreyoconnor** [comment]
Incremented version and deployed to hackage:

* http://hackage.haskell.org/package/vty
* http://hackage.haskell.org/package/vty-examples

:+1:

**Comment by jtdaugherty** [comment]
Thank you!
