### ISSUE TITLE
Cursor placement with multi-column characters

### ISSUE THREAD

**Issue by jtdaugherty** [coreyoconnor/vty#94]
At some point `vty` started being smarter about multi-column characters and I didn't notice.  Now I'm trying out adding multi-column character support to `brick` and I have encountered something interesting.

`brick` has to do layout of Vty images, and sometimes those images come with cursor placement requests.  So we might have to lay out two images as follows:
```
"寬字" (no cursor) next to "foobar" (cursor location (0, 0))
```
so that the final result would be
```
寬字foobar
```
with the cursor placed on the `f`.  The (currently broken) way `brick` figures out that the new cursor location should be on the `f` is by adding the `imageWidth` of `"寬字"` to the requested cursor position `(0,0)` to determine a new position.  This approach works when all characters are single-column.

But the problem is that the width returned by `imageWidth` is the physical width of the image (in display columns), but the position needed for cursor placement is in characters.  So I end up getting `4+0=4` rather than `2+0=2` and my cursor is placed too far to the right.

I don't know how to get this right with the current API.  Am I missing something?

**Comment by jtdaugherty** [comment]
(CC https://github.com/jtdaugherty/brick/issues/61)

**Comment by glguy** [comment]
My use-case for rendering a text box that overflows by scrolling requires me to work around this clever behavior. Basically I have to compute the opposite transformation and then use that when requesting a cursor position.

I working around this feature with the following code: https://github.com/glguy/irc-core/blob/v2/src/Client/Image/Textbox.hs

Even better than inverting the operation would be a setting to turn off this more clever behavior.
